### ISSUE TITLE
refresh failed: value for 'host.type' must be one of `DATA_NODE`, `MASTER_NODE`, `TYPE_UNSPECIFIED`, not ``

### ISSUE THREAD

**Issue by fitospark** [yandex-cloud/crossplane-provider-yc#10]
Good afternoon. After installing Elastic, after a while the state of Reconcile goes into Error, without any changes or edits.

Behavior example:
1. Install. status:

Conditions:
    Last Transition Time: 2022-08-09T13:25:27Z
    Reason: ReconcileSuccess
    Status: True
    Type: Synced

`Normal UpdatedExternalResource 8m managed/mdb.yandex-cloud.jet.crossplane.io/v1alpha1, kind=elasticsearchcluster  Successfully requested update of external resource`

2. After some time, about 10-15 hours:

Conditions:
    Last Transition Time: 2022-08-10T04:05:36Z
    Message: observe failed: cannot run refresh: refresh failed: value for 'host.type' must be one of `TYPE_UNSPECIFIED`, `DATA_NODE`, `MASTER_NODE`, not ``: : File name: main.tf.json
    Reason: ReconcileError
    Status: False
    Type: Synced

Events:
Warning  CannotObserveExternalResource  29m (x12 over 70m)    managed/mdb.yandex-cloud.jet.crossplane.io/v1alpha1, kind=elasticsearchcluster  cannot run refresh: refresh failed: value for 'host.type' must be one of `MASTER_NODE`, `TYPE_UNSPECIFIED`, `DATA_NODE`, not ``: : File name: main.tf.json

Warning  CannotObserveExternalResource  4m43s (x92 over 74m)  managed/mdb.yandex-cloud.jet.crossplane.io/v1alpha1, kind=elasticsearchcluster  cannot run refresh: refresh failed: value for 'host.type' must be one of `TYPE_UNSPECIFIED`, `DATA_NODE`, `MASTER_NODE`, not ``: : File name: main.tf.json`

However, no remedial action was taken.

3. Code Example:

```
    host:
      - assignPublicIp: {{ .Values.efk.PublicIp }}
        name: {{ .Values.efk.Name }}
        subnetIdRef:
          name: {{ .Values.yc.SubnetB }}
        type: "DATA_NODE"
        zone: {{ .Values.yc.HostAvailabilityZoneB }}
    name: {{ .Values.efk.Name }}
```
