### ISSUE TITLE
Crossplane Message - no matches for kind "Queue" in version "message.yandex-cloud.jet.crossplane.io/v1alpha1"

### ISSUE THREAD

**Issue by allanian** [yandex-cloud/crossplane-provider-yc#16]
Hello, was trying to create message kafka with crossplane
Crossplane install from github helm chart
Provider installed with:
```
kubectl crossplane update provider crp0kch415f0lke009ft-crossplane-provider-jet-yc v0.1.37
```
```
apiVersion: message.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Queue
metadata:
  name: queue-test
spec:
  forProvider:
    name: queue-fines
    secretKeySecretRef:
      name: sa-key-conn
      namespace: infra-crossplane
      key: attribute.secret_key
    accessKeyRef:
      name: example-sa-static-key
```
Error:
error: resource mapping not found for name: "queue-test" namespace: "" from "queue.yaml": no matches for kind "Queue" in version "message.yandex-cloud.jet.crossplane.io/v1alpha1"
ensure CRDs are installed first
